//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epiphany.Strings {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epiphany.Strings.AppStrings", typeof(AppStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reads for Windows.
        /// </summary>
        public static string AboutAppTitle {
            get {
                return ResourceManager.GetString("AboutAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like on Facebook.
        /// </summary>
        public static string AboutLikeonFBButtonText {
            get {
                return ResourceManager.GetString("AboutLikeonFBButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate the App.
        /// </summary>
        public static string AboutRateButtonText {
            get {
                return ResourceManager.GetString("AboutRateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: 3.0.
        /// </summary>
        public static string AboutVersionString {
            get {
                return ResourceManager.GetString("AboutVersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AddBookshelfButtonText {
            get {
                return ResourceManager.GetString("AddBookshelfButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD FRIEND.
        /// </summary>
        public static string AddFriendButtonLabel {
            get {
                return ResourceManager.GetString("AddFriendButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add to shelf.
        /// </summary>
        public static string AddToShelfTitle {
            get {
                return ResourceManager.GetString("AddToShelfTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to age.
        /// </summary>
        public static string AgeText {
            get {
                return ResourceManager.GetString("AgeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AppBarAboutText {
            get {
                return ResourceManager.GetString("AppBarAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add friend.
        /// </summary>
        public static string AppBarAddFriendText {
            get {
                return ResourceManager.GetString("AppBarAddFriendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarAddText {
            get {
                return ResourceManager.GetString("AppBarAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh feed.
        /// </summary>
        public static string AppBarButtonRefreshFeedText {
            get {
                return ResourceManager.GetString("AppBarButtonRefreshFeedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scan.
        /// </summary>
        public static string AppBarButtonScanText {
            get {
                return ResourceManager.GetString("AppBarButtonScanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string AppBarButtonSearchText {
            get {
                return ResourceManager.GetString("AppBarButtonSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string AppBarButtonSettingsText {
            get {
                return ResourceManager.GetString("AppBarButtonSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create.
        /// </summary>
        public static string AppBarCreateText {
            get {
                return ResourceManager.GetString("AppBarCreateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go home.
        /// </summary>
        public static string AppBarHomeText {
            get {
                return ResourceManager.GetString("AppBarHomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin.
        /// </summary>
        public static string AppBarPinText {
            get {
                return ResourceManager.GetString("AppBarPinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string AppBarRefreshEventsButtonText {
            get {
                return ResourceManager.GetString("AppBarRefreshEventsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string AppBarRefreshText {
            get {
                return ResourceManager.GetString("AppBarRefreshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign out.
        /// </summary>
        public static string AppBarSignOutText {
            get {
                return ResourceManager.GetString("AppBarSignOutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sort.
        /// </summary>
        public static string AppBarSortText {
            get {
                return ResourceManager.GetString("AppBarSortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to submit.
        /// </summary>
        public static string AppBarSubmitText {
            get {
                return ResourceManager.GetString("AppBarSubmitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unpin.
        /// </summary>
        public static string AppBarUnpinText {
            get {
                return ResourceManager.GetString("AppBarUnpinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reads.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reads.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AuthorAboutTitle {
            get {
                return ResourceManager.GetString("AuthorAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average rating.
        /// </summary>
        public static string AuthorAverageRating {
            get {
                return ResourceManager.GetString("AuthorAverageRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to books.
        /// </summary>
        public static string AuthorBooksTitle {
            get {
                return ResourceManager.GetString("AuthorBooksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to born.
        /// </summary>
        public static string AuthorBorn {
            get {
                return ResourceManager.GetString("AuthorBorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gender.
        /// </summary>
        public static string AuthorGender {
            get {
                return ResourceManager.GetString("AuthorGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hometown.
        /// </summary>
        public static string AuthorHometown {
            get {
                return ResourceManager.GetString("AuthorHometown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to influences.
        /// </summary>
        public static string AuthorInfluences {
            get {
                return ResourceManager.GetString("AuthorInfluences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fans.
        /// </summary>
        public static string AuthorNumberOfFans {
            get {
                return ResourceManager.GetString("AuthorNumberOfFans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to works.
        /// </summary>
        public static string AuthorNumberOfWorks {
            get {
                return ResourceManager.GetString("AuthorNumberOfWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT.
        /// </summary>
        public static string AuthorPivotAboutHeader {
            get {
                return ResourceManager.GetString("AuthorPivotAboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOKS.
        /// </summary>
        public static string AuthorPivotBooksHeader {
            get {
                return ResourceManager.GetString("AuthorPivotBooksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to authors.
        /// </summary>
        public static string AuthorsHeaderText {
            get {
                return ResourceManager.GetString("AuthorsHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESCRIPTION.
        /// </summary>
        public static string BookDescriptionSectionHeader {
            get {
                return ResourceManager.GetString("BookDescriptionSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT.
        /// </summary>
        public static string BookPivotAboutHeader {
            get {
                return ResourceManager.GetString("BookPivotAboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REVIEWS.
        /// </summary>
        public static string BookPivotReviewsHeader {
            get {
                return ResourceManager.GetString("BookPivotReviewsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIMILAR.
        /// </summary>
        public static string BookPivotSimilarHeader {
            get {
                return ResourceManager.GetString("BookPivotSimilarHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POPULAR SHELVES.
        /// </summary>
        public static string BookPopularShelvesSectionHeader {
            get {
                return ResourceManager.GetString("BookPopularShelvesSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string BookSearchTypeAll {
            get {
                return ResourceManager.GetString("BookSearchTypeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string BookSearchTypeAuthor {
            get {
                return ResourceManager.GetString("BookSearchTypeAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string BookSearchTypeTitle {
            get {
                return ResourceManager.GetString("BookSearchTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string BooksFilterAuthor {
            get {
                return ResourceManager.GetString("BooksFilterAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Rating.
        /// </summary>
        public static string BooksFilterAverageRating {
            get {
                return ResourceManager.GetString("BooksFilterAverageRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover.
        /// </summary>
        public static string BooksFilterCover {
            get {
                return ResourceManager.GetString("BooksFilterCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Added.
        /// </summary>
        public static string BooksFilterDateAdded {
            get {
                return ResourceManager.GetString("BooksFilterDateAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Read.
        /// </summary>
        public static string BooksFilterDateRead {
            get {
                return ResourceManager.GetString("BooksFilterDateRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Started.
        /// </summary>
        public static string BooksFilterDateStarted {
            get {
                return ResourceManager.GetString("BooksFilterDateStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHOW BOOKS SORTED BY.
        /// </summary>
        public static string BooksFilterFlyoutTitle {
            get {
                return ResourceManager.GetString("BooksFilterFlyoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Pages.
        /// </summary>
        public static string BooksFilterNumPages {
            get {
                return ResourceManager.GetString("BooksFilterNumPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Ratings.
        /// </summary>
        public static string BooksFilterNumRatings {
            get {
                return ResourceManager.GetString("BooksFilterNumRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owned.
        /// </summary>
        public static string BooksFilterOwned {
            get {
                return ResourceManager.GetString("BooksFilterOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string BooksFilterRating {
            get {
                return ResourceManager.GetString("BooksFilterRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Count.
        /// </summary>
        public static string BooksFilterReadCount {
            get {
                return ResourceManager.GetString("BooksFilterReadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string BooksFilterReview {
            get {
                return ResourceManager.GetString("BooksFilterReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string BooksFilterTitle {
            get {
                return ResourceManager.GetString("BooksFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Published.
        /// </summary>
        public static string BooksFilterYearPublished {
            get {
                return ResourceManager.GetString("BooksFilterYearPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOKSHELVES.
        /// </summary>
        public static string BookshelvesSectionTitle {
            get {
                return ResourceManager.GetString("BookshelvesSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIMILAR BOOKS.
        /// </summary>
        public static string BookSimilarBooksSectionHeader {
            get {
                return ResourceManager.GetString("BookSimilarBooksSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order by.
        /// </summary>
        public static string BooksOrderHeader {
            get {
                return ResourceManager.GetString("BooksOrderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        public static string BooksSortHeader {
            get {
                return ResourceManager.GetString("BooksSortHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string BooksSortOrderAscending {
            get {
                return ResourceManager.GetString("BooksSortOrderAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decreasing.
        /// </summary>
        public static string BooksSortOrderDecreasing {
            get {
                return ResourceManager.GetString("BooksSortOrderDecreasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string BooksSortOrderDescending {
            get {
                return ResourceManager.GetString("BooksSortOrderDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER BOOKS BY.
        /// </summary>
        public static string BooksSortOrderFlyoutTitle {
            get {
                return ResourceManager.GetString("BooksSortOrderFlyoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest.
        /// </summary>
        public static string BooksSortOrderHighest {
            get {
                return ResourceManager.GetString("BooksSortOrderHighest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increasing.
        /// </summary>
        public static string BooksSortOrderIncreasing {
            get {
                return ResourceManager.GetString("BooksSortOrderIncreasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowest.
        /// </summary>
        public static string BooksSortOrderLowest {
            get {
                return ResourceManager.GetString("BooksSortOrderLowest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newest.
        /// </summary>
        public static string BooksSortOrderNewest {
            get {
                return ResourceManager.GetString("BooksSortOrderNewest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldest.
        /// </summary>
        public static string BooksSortOrderOldest {
            get {
                return ResourceManager.GetString("BooksSortOrderOldest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bookshelves.
        /// </summary>
        public static string BooksTitle {
            get {
                return ResourceManager.GetString("BooksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in with Goodreads.
        /// </summary>
        public static string ButtonSignIn {
            get {
                return ResourceManager.GetString("ButtonSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less.
        /// </summary>
        public static string CollapsableTextLessButtonText {
            get {
                return ResourceManager.GetString("CollapsableTextLessButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string CollapsableTextMoreButtonText {
            get {
                return ResourceManager.GetString("CollapsableTextMoreButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} commented on a review:.
        /// </summary>
        public static string CommentFeedItemActionText {
            get {
                return ResourceManager.GetString("CommentFeedItemActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string CommentText {
            get {
                return ResourceManager.GetString("CommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOKS YOU ARE READING.
        /// </summary>
        public static string CurrentlyReadingSectionTitle {
            get {
                return ResourceManager.GetString("CurrentlyReadingSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Transparent Tile.
        /// </summary>
        public static string EnableTransparentTileHeader {
            get {
                return ResourceManager.GetString("EnableTransparentTileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LITERARY EVENTS.
        /// </summary>
        public static string EventsTitle {
            get {
                return ResourceManager.GetString("EventsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorite books.
        /// </summary>
        public static string FavoriteBooksText {
            get {
                return ResourceManager.GetString("FavoriteBooksText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress: .
        /// </summary>
        public static string FeedBookProgressText {
            get {
                return ResourceManager.GetString("FeedBookProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string FeedCommentActionText {
            get {
                return ResourceManager.GetString("FeedCommentActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        public static string FeedLikeActionText {
            get {
                return ResourceManager.GetString("FeedLikeActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEED OPTIONS.
        /// </summary>
        public static string FeedOptionsHeaderText {
            get {
                return ResourceManager.GetString("FeedOptionsHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string FeedOptionsShowUpdatesForAllText {
            get {
                return ResourceManager.GetString("FeedOptionsShowUpdatesForAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to books.
        /// </summary>
        public static string FeedOptionsShowUpdatesForBooksText {
            get {
                return ResourceManager.GetString("FeedOptionsShowUpdatesForBooksText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show updates for.
        /// </summary>
        public static string FeedOptionsShowUpdatesForHeader {
            get {
                return ResourceManager.GetString("FeedOptionsShowUpdatesForHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reviews.
        /// </summary>
        public static string FeedOptionsShowUpdatesForReviewsText {
            get {
                return ResourceManager.GetString("FeedOptionsShowUpdatesForReviewsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statuses.
        /// </summary>
        public static string FeedOptionsShowUpdatesForStatusesText {
            get {
                return ResourceManager.GetString("FeedOptionsShowUpdatesForStatusesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to followers.
        /// </summary>
        public static string FeedOptionsShowUpdatesFromFollowersText {
            get {
                return ResourceManager.GetString("FeedOptionsShowUpdatesFromFollowersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friends.
        /// </summary>
        public static string FeedOptionsShowUpdatesFromFriendsText {
            get {
                return ResourceManager.GetString("FeedOptionsShowUpdatesFromFriendsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show updates from.
        /// </summary>
        public static string FeedOptionsShowUpdatesFromHeader {
            get {
                return ResourceManager.GetString("FeedOptionsShowUpdatesFromHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to top friends.
        /// </summary>
        public static string FeedOptionsShowUpdatesFromTopFriendsText {
            get {
                return ResourceManager.GetString("FeedOptionsShowUpdatesFromTopFriendsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to showing {0} from {1}.
        /// </summary>
        public static string FeedOptionsSummaryText {
            get {
                return ResourceManager.GetString("FeedOptionsSummaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string FeedViewInBrowserActionText {
            get {
                return ResourceManager.GetString("FeedViewInBrowserActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to read.
        /// </summary>
        public static string FeedWantToReadButtonText {
            get {
                return ResourceManager.GetString("FeedWantToReadButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} followers.
        /// </summary>
        public static string FollowersCountStringFormat {
            get {
                return ResourceManager.GetString("FollowersCountStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOLLOWING.
        /// </summary>
        public static string FollowingReviewsButtonLabel {
            get {
                return ResourceManager.GetString("FollowingReviewsButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOLLOW.
        /// </summary>
        public static string FollowReviewsButtonLabel {
            get {
                return ResourceManager.GetString("FollowReviewsButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is now friends with:.
        /// </summary>
        public static string FriendFeedItemActionText {
            get {
                return ResourceManager.GetString("FriendFeedItemActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friend status.
        /// </summary>
        public static string FriendStatusText {
            get {
                return ResourceManager.GetString("FriendStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friends.
        /// </summary>
        public static string FriendsTitle {
            get {
                return ResourceManager.GetString("FriendsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gender.
        /// </summary>
        public static string GenderText {
            get {
                return ResourceManager.GetString("GenderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string HomeEventsTitle {
            get {
                return ResourceManager.GetString("HomeEventsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string HomeFriendsTitle {
            get {
                return ResourceManager.GetString("HomeFriendsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string HomeGroupsTitle {
            get {
                return ResourceManager.GetString("HomeGroupsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Books.
        /// </summary>
        public static string HomeMyBooksTitle {
            get {
                return ResourceManager.GetString("HomeMyBooksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string HomeMyProfileTitle {
            get {
                return ResourceManager.GetString("HomeMyProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendations.
        /// </summary>
        public static string HomeRecommendationsTitle {
            get {
                return ResourceManager.GetString("HomeRecommendationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This book is in your shelf.
        /// </summary>
        public static string InShelfText {
            get {
                return ResourceManager.GetString("InShelfText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interests.
        /// </summary>
        public static string InterestsText {
            get {
                return ResourceManager.GetString("InterestsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to join date.
        /// </summary>
        public static string JoinDateText {
            get {
                return ResourceManager.GetString("JoinDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location.
        /// </summary>
        public static string LocationText {
            get {
                return ResourceManager.GetString("LocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string MenuHeader {
            get {
                return ResourceManager.GetString("MenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}d.
        /// </summary>
        public static string NDaysAgoText {
            get {
                return ResourceManager.GetString("NDaysAgoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}h.
        /// </summary>
        public static string NHoursAgoText {
            get {
                return ResourceManager.GetString("NHoursAgoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}m.
        /// </summary>
        public static string NMinutesAgoText {
            get {
                return ResourceManager.GetString("NMinutesAgoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}mon.
        /// </summary>
        public static string NMonthsAgoText {
            get {
                return ResourceManager.GetString("NMonthsAgoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no bookshelves!.
        /// </summary>
        public static string NoBookshelvesMessage {
            get {
                return ResourceManager.GetString("NoBookshelvesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add some friends on Goodreads to see your friend updates here!.
        /// </summary>
        public static string NoFeedMessage {
            get {
                return ResourceManager.GetString("NoFeedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no friends!.
        /// </summary>
        public static string NoFriendsMessage {
            get {
                return ResourceManager.GetString("NoFriendsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No search results.
        /// </summary>
        public static string NoSearchResultsText {
            get {
                return ResourceManager.GetString("NoSearchResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no updates!.
        /// </summary>
        public static string NoUpdatesMessage {
            get {
                return ResourceManager.GetString("NoUpdatesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}s.
        /// </summary>
        public static string NSecondsAgoText {
            get {
                return ResourceManager.GetString("NSecondsAgoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friends.
        /// </summary>
        public static string NumberedItemFriendPlural {
            get {
                return ResourceManager.GetString("NumberedItemFriendPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friend.
        /// </summary>
        public static string NumberedItemFriendSingular {
            get {
                return ResourceManager.GetString("NumberedItemFriendSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to groups.
        /// </summary>
        public static string NumberedItemGroupPlural {
            get {
                return ResourceManager.GetString("NumberedItemGroupPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group.
        /// </summary>
        public static string NumberedItemGroupSingular {
            get {
                return ResourceManager.GetString("NumberedItemGroupSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}y.
        /// </summary>
        public static string NYearsAgoText {
            get {
                return ResourceManager.GetString("NYearsAgoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOKS YOU OWN.
        /// </summary>
        public static string OwnedBooksSectionTitle {
            get {
                return ResourceManager.GetString("OwnedBooksSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pending approval.
        /// </summary>
        public static string PendingApprovalText {
            get {
                return ResourceManager.GetString("PendingApprovalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile.
        /// </summary>
        public static string ProfileAboutTitle {
            get {
                return ResourceManager.GetString("ProfileAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bookshelves.
        /// </summary>
        public static string ProfileBookshelvesTitle {
            get {
                return ResourceManager.GetString("ProfileBookshelvesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRIENDS.
        /// </summary>
        public static string ProfileButtonFriendsLabel {
            get {
                return ResourceManager.GetString("ProfileButtonFriendsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROUPS.
        /// </summary>
        public static string ProfileButtonGroupsLabel {
            get {
                return ResourceManager.GetString("ProfileButtonGroupsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REVIEWS.
        /// </summary>
        public static string ProfileButtonReviewsLabel {
            get {
                return ResourceManager.GetString("ProfileButtonReviewsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHELVES.
        /// </summary>
        public static string ProfileButtonShelvesLabel {
            get {
                return ResourceManager.GetString("ProfileButtonShelvesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no posts to show here!.
        /// </summary>
        public static string ProfileEmptyRecentUpdatesMessage {
            get {
                return ResourceManager.GetString("ProfileEmptyRecentUpdatesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string ProfilePivotHeaderAbout {
            get {
                return ResourceManager.GetString("ProfilePivotHeaderAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string ProfilePivotHeaderBooks {
            get {
                return ResourceManager.GetString("ProfilePivotHeaderBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        public static string ProfilePivotHeaderPosts {
            get {
                return ResourceManager.GetString("ProfilePivotHeaderPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAVORITE AUTHORS.
        /// </summary>
        public static string ProfileSectionHeaderFavoriteAuthors {
            get {
                return ResourceManager.GetString("ProfileSectionHeaderFavoriteAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POSTS.
        /// </summary>
        public static string ProfileSectionHeaderPosts {
            get {
                return ResourceManager.GetString("ProfileSectionHeaderPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updates.
        /// </summary>
        public static string ProfileUpdatesTitle {
            get {
                return ResourceManager.GetString("ProfileUpdatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ratings.
        /// </summary>
        public static string RatingsCountStringFormat {
            get {
                return ResourceManager.GetString("RatingsCountStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOKS YOU READ THIS YEAR.
        /// </summary>
        public static string ReadingChallengeSectionTitle {
            get {
                return ResourceManager.GetString("ReadingChallengeSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} started reading:.
        /// </summary>
        public static string ReadStatusFeedItemCurrentlyReadingActionText {
            get {
                return ResourceManager.GetString("ReadStatusFeedItemCurrentlyReadingActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has read:.
        /// </summary>
        public static string ReadStatusFeedItemHasReadActionText {
            get {
                return ResourceManager.GetString("ReadStatusFeedItemHasReadActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} wants to read:.
        /// </summary>
        public static string ReadStatusFeedItemToReadActionText {
            get {
                return ResourceManager.GetString("ReadStatusFeedItemToReadActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from shelf.
        /// </summary>
        public static string RemoveFromShelfButtonText {
            get {
                return ResourceManager.GetString("RemoveFromShelfButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRIEND REQUEST PENDING.
        /// </summary>
        public static string RequestPendingText {
            get {
                return ResourceManager.GetString("RequestPendingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        public static string RetryLoginButtonText {
            get {
                return ResourceManager.GetString("RetryLoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} rated a book.
        /// </summary>
        public static string ReviewFeedItemActionText {
            get {
                return ResourceManager.GetString("ReviewFeedItemActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelved as: .
        /// </summary>
        public static string ReviewShelvedAsText {
            get {
                return ResourceManager.GetString("ReviewShelvedAsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s Review.
        /// </summary>
        public static string ReviewTitleFormat {
            get {
                return ResourceManager.GetString("ReviewTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find books, authors.
        /// </summary>
        public static string SearchBoxPlaceholderText {
            get {
                return ResourceManager.GetString("SearchBoxPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refine:.
        /// </summary>
        public static string SearchFilterHeader {
            get {
                return ResourceManager.GetString("SearchFilterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search did not return any results.
        /// </summary>
        public static string SearchNoResultsMessage {
            get {
                return ResourceManager.GetString("SearchNoResultsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share.
        /// </summary>
        public static string SearchResultItemFlyoutShare {
            get {
                return ResourceManager.GetString("SearchResultItemFlyoutShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view author.
        /// </summary>
        public static string SearchResultItemFlyoutViewAuthor {
            get {
                return ResourceManager.GetString("SearchResultItemFlyoutViewAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to find books by title,author.
        /// </summary>
        public static string SearchTextBoxHint {
            get {
                return ResourceManager.GetString("SearchTextBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string SearchTitle {
            get {
                return ResourceManager.GetString("SearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pick a search type.
        /// </summary>
        public static string SearchTypeFullModeHeader {
            get {
                return ResourceManager.GetString("SearchTypeFullModeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to read.
        /// </summary>
        public static string SearchWantToReadButtonText {
            get {
                return ResourceManager.GetString("SearchWantToReadButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT.
        /// </summary>
        public static string SettingsAboutHeaderTitle {
            get {
                return ResourceManager.GetString("SettingsAboutHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APP.
        /// </summary>
        public static string SettingsAppHeaderTitle {
            get {
                return ResourceManager.GetString("SettingsAppHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable diagnostic logging.
        /// </summary>
        public static string SettingsEnableLoggingHeader {
            get {
                return ResourceManager.GetString("SettingsEnableLoggingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable transparent tile.
        /// </summary>
        public static string SettingsEnableTransparentTileHeader {
            get {
                return ResourceManager.GetString("SettingsEnableTransparentTileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Reads to use my location.
        /// </summary>
        public static string SettingsLocationPermissionHeader {
            get {
                return ResourceManager.GetString("SettingsLocationPermissionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No notifications.
        /// </summary>
        public static string SettingsNotificationPreference1 {
            get {
                return ResourceManager.GetString("SettingsNotificationPreference1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toasts and tile count.
        /// </summary>
        public static string SettingsNotificationPreference2 {
            get {
                return ResourceManager.GetString("SettingsNotificationPreference2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile count only.
        /// </summary>
        public static string SettingsNotificationPreference3 {
            get {
                return ResourceManager.GetString("SettingsNotificationPreference3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I prefer to receive.
        /// </summary>
        public static string SettingsNotificationPreferenceHeader {
            get {
                return ResourceManager.GetString("SettingsNotificationPreferenceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A book has been shared with you.
        /// </summary>
        public static string ShareBookTitle {
            get {
                return ResourceManager.GetString("ShareBookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start sharing. Please try again later.
        /// </summary>
        public static string SharingFailedMessage {
            get {
                return ResourceManager.GetString("SharingFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is taking longer than expected. This could be due to a slow network connection..
        /// </summary>
        public static string SigningInStuckMessage {
            get {
                return ResourceManager.GetString("SigningInStuckMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        public static string TabHeaderCommunity {
            get {
                return ResourceManager.GetString("TabHeaderCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string TabHeaderHome {
            get {
                return ResourceManager.GetString("TabHeaderHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string TabHeaderMore {
            get {
                return ResourceManager.GetString("TabHeaderMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Books.
        /// </summary>
        public static string TabHeaderMyBooks {
            get {
                return ResourceManager.GetString("TabHeaderMyBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reads works best when you sign in to Goodreads to show you updates from your friends and people you follow..
        /// </summary>
        public static string TabHomeSignInText {
            get {
                return ResourceManager.GetString("TabHomeSignInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By logging in with your Goodreads account, you can personalize and organize your books. You can view all your bookshelves and you can update books that you are currently reading. You can also add or remove books from your shelves..
        /// </summary>
        public static string TabMyBooksSignInText {
            get {
                return ResourceManager.GetString("TabMyBooksSignInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string TopButtonText {
            get {
                return ResourceManager.GetString("TopButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s Friends.
        /// </summary>
        public static string UserFriendsTitleFormat {
            get {
                return ResourceManager.GetString("UserFriendsTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        public static string UsernameText {
            get {
                return ResourceManager.GetString("UsernameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is {1}% done with:.
        /// </summary>
        public static string UserStatusFeedItemActionText {
            get {
                return ResourceManager.GetString("UserStatusFeedItemActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has finished reading:.
        /// </summary>
        public static string UserStatusFeedItemFinishedActionText {
            get {
                return ResourceManager.GetString("UserStatusFeedItemFinishedActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view friends.
        /// </summary>
        public static string ViewFriendsText {
            get {
                return ResourceManager.GetString("ViewFriendsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view groups.
        /// </summary>
        public static string ViewGroupsText {
            get {
                return ResourceManager.GetString("ViewGroupsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view in goodreads.
        /// </summary>
        public static string ViewInGoodreadsText {
            get {
                return ResourceManager.GetString("ViewInGoodreadsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s New.
        /// </summary>
        public static string WhatsNewHeader {
            get {
                return ResourceManager.GetString("WhatsNewHeader", resourceCulture);
            }
        }
    }
}
