//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epiphany.Strings {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epiphany.Strings.AppStrings", typeof(AppStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about {0} hours ago.
        /// </summary>
        public static string AboutNHoursAgoText {
            get {
                return ResourceManager.GetString("AboutNHoursAgoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AddBookshelfButtonText {
            get {
                return ResourceManager.GetString("AddBookshelfButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add to shelf.
        /// </summary>
        public static string AddToShelfTitle {
            get {
                return ResourceManager.GetString("AddToShelfTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to age.
        /// </summary>
        public static string AgeText {
            get {
                return ResourceManager.GetString("AgeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AppBarAboutText {
            get {
                return ResourceManager.GetString("AppBarAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add friend.
        /// </summary>
        public static string AppBarAddFriendText {
            get {
                return ResourceManager.GetString("AppBarAddFriendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarAddText {
            get {
                return ResourceManager.GetString("AppBarAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scan.
        /// </summary>
        public static string AppBarButtonScanText {
            get {
                return ResourceManager.GetString("AppBarButtonScanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string AppBarButtonSearchText {
            get {
                return ResourceManager.GetString("AppBarButtonSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string AppBarButtonSettingsText {
            get {
                return ResourceManager.GetString("AppBarButtonSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create.
        /// </summary>
        public static string AppBarCreateText {
            get {
                return ResourceManager.GetString("AppBarCreateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go home.
        /// </summary>
        public static string AppBarHomeText {
            get {
                return ResourceManager.GetString("AppBarHomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin.
        /// </summary>
        public static string AppBarPinText {
            get {
                return ResourceManager.GetString("AppBarPinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string AppBarRefreshEventsButtonText {
            get {
                return ResourceManager.GetString("AppBarRefreshEventsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string AppBarRefreshText {
            get {
                return ResourceManager.GetString("AppBarRefreshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign out.
        /// </summary>
        public static string AppBarSignOutText {
            get {
                return ResourceManager.GetString("AppBarSignOutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sort.
        /// </summary>
        public static string AppBarSortText {
            get {
                return ResourceManager.GetString("AppBarSortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to submit.
        /// </summary>
        public static string AppBarSubmitText {
            get {
                return ResourceManager.GetString("AppBarSubmitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reads.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reads.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AuthorAboutTitle {
            get {
                return ResourceManager.GetString("AuthorAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average rating.
        /// </summary>
        public static string AuthorAverageRating {
            get {
                return ResourceManager.GetString("AuthorAverageRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to books.
        /// </summary>
        public static string AuthorBooksTitle {
            get {
                return ResourceManager.GetString("AuthorBooksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to born.
        /// </summary>
        public static string AuthorBorn {
            get {
                return ResourceManager.GetString("AuthorBorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gender.
        /// </summary>
        public static string AuthorGender {
            get {
                return ResourceManager.GetString("AuthorGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hometown.
        /// </summary>
        public static string AuthorHometown {
            get {
                return ResourceManager.GetString("AuthorHometown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to influences.
        /// </summary>
        public static string AuthorInfluences {
            get {
                return ResourceManager.GetString("AuthorInfluences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fans.
        /// </summary>
        public static string AuthorNumberOfFans {
            get {
                return ResourceManager.GetString("AuthorNumberOfFans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to works.
        /// </summary>
        public static string AuthorNumberOfWorks {
            get {
                return ResourceManager.GetString("AuthorNumberOfWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to authors.
        /// </summary>
        public static string AuthorsHeaderText {
            get {
                return ResourceManager.GetString("AuthorsHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string BookSearchTypeAll {
            get {
                return ResourceManager.GetString("BookSearchTypeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string BookSearchTypeAuthor {
            get {
                return ResourceManager.GetString("BookSearchTypeAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string BookSearchTypeTitle {
            get {
                return ResourceManager.GetString("BookSearchTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bookshelves.
        /// </summary>
        public static string BooksTitle {
            get {
                return ResourceManager.GetString("BooksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in with Goodreads.
        /// </summary>
        public static string ButtonSignIn {
            get {
                return ResourceManager.GetString("ButtonSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} commented on a review:.
        /// </summary>
        public static string CommentFeedItemActionText {
            get {
                return ResourceManager.GetString("CommentFeedItemActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string CommentText {
            get {
                return ResourceManager.GetString("CommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Transparent Tile.
        /// </summary>
        public static string EnableTransparentTileHeader {
            get {
                return ResourceManager.GetString("EnableTransparentTileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorite books.
        /// </summary>
        public static string FavoriteBooksText {
            get {
                return ResourceManager.GetString("FavoriteBooksText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is now friends with:.
        /// </summary>
        public static string FriendFeedItemActionText {
            get {
                return ResourceManager.GetString("FriendFeedItemActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friend status.
        /// </summary>
        public static string FriendStatusText {
            get {
                return ResourceManager.GetString("FriendStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friends.
        /// </summary>
        public static string FriendsTitle {
            get {
                return ResourceManager.GetString("FriendsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gender.
        /// </summary>
        public static string GenderText {
            get {
                return ResourceManager.GetString("GenderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to events.
        /// </summary>
        public static string HomeEventsTitle {
            get {
                return ResourceManager.GetString("HomeEventsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friends.
        /// </summary>
        public static string HomeFriendsTitle {
            get {
                return ResourceManager.GetString("HomeFriendsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to groups.
        /// </summary>
        public static string HomeGroupsTitle {
            get {
                return ResourceManager.GetString("HomeGroupsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Books.
        /// </summary>
        public static string HomeMyBooksTitle {
            get {
                return ResourceManager.GetString("HomeMyBooksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my profile.
        /// </summary>
        public static string HomeMyProfileTitle {
            get {
                return ResourceManager.GetString("HomeMyProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interests.
        /// </summary>
        public static string InterestsText {
            get {
                return ResourceManager.GetString("InterestsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to join date.
        /// </summary>
        public static string JoinDateText {
            get {
                return ResourceManager.GetString("JoinDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to just a moment ago.
        /// </summary>
        public static string JustAMomentAgoText {
            get {
                return ResourceManager.GetString("JustAMomentAgoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to like on facebook.
        /// </summary>
        public static string LikeonFBButtonText {
            get {
                return ResourceManager.GetString("LikeonFBButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Epiphany to use my location.
        /// </summary>
        public static string LocationPermissionHeader {
            get {
                return ResourceManager.GetString("LocationPermissionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location.
        /// </summary>
        public static string LocationText {
            get {
                return ResourceManager.GetString("LocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string MenuHeader {
            get {
                return ResourceManager.GetString("MenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        public static string NDaysAgoText {
            get {
                return ResourceManager.GetString("NDaysAgoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes ago.
        /// </summary>
        public static string NMinutesAgoText {
            get {
                return ResourceManager.GetString("NMinutesAgoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} months ago.
        /// </summary>
        public static string NMonthsAgoText {
            get {
                return ResourceManager.GetString("NMonthsAgoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no bookshelves!.
        /// </summary>
        public static string NoBookshelvesMessage {
            get {
                return ResourceManager.GetString("NoBookshelvesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add some friends on Goodreads to see your friend updates here!.
        /// </summary>
        public static string NoFeedMessage {
            get {
                return ResourceManager.GetString("NoFeedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no friends!.
        /// </summary>
        public static string NoFriendsMessage {
            get {
                return ResourceManager.GetString("NoFriendsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No search results.
        /// </summary>
        public static string NoSearchResultsText {
            get {
                return ResourceManager.GetString("NoSearchResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No notifications.
        /// </summary>
        public static string NotificationPreference1 {
            get {
                return ResourceManager.GetString("NotificationPreference1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toasts and tile count.
        /// </summary>
        public static string NotificationPreference2 {
            get {
                return ResourceManager.GetString("NotificationPreference2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile count only.
        /// </summary>
        public static string NotificationPreference3 {
            get {
                return ResourceManager.GetString("NotificationPreference3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I prefer to receive.
        /// </summary>
        public static string NotificationPreferenceHeader {
            get {
                return ResourceManager.GetString("NotificationPreferenceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no updates!.
        /// </summary>
        public static string NoUpdatesMessage {
            get {
                return ResourceManager.GetString("NoUpdatesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds ago.
        /// </summary>
        public static string NSecondsAgoText {
            get {
                return ResourceManager.GetString("NSecondsAgoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friends.
        /// </summary>
        public static string NumberedItemFriendPlural {
            get {
                return ResourceManager.GetString("NumberedItemFriendPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friend.
        /// </summary>
        public static string NumberedItemFriendSingular {
            get {
                return ResourceManager.GetString("NumberedItemFriendSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to groups.
        /// </summary>
        public static string NumberedItemGroupPlural {
            get {
                return ResourceManager.GetString("NumberedItemGroupPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group.
        /// </summary>
        public static string NumberedItemGroupSingular {
            get {
                return ResourceManager.GetString("NumberedItemGroupSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years ago.
        /// </summary>
        public static string NYearsAgoText {
            get {
                return ResourceManager.GetString("NYearsAgoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day ago.
        /// </summary>
        public static string OneDayAgoText {
            get {
                return ResourceManager.GetString("OneDayAgoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour ago.
        /// </summary>
        public static string OneHourAgoText {
            get {
                return ResourceManager.GetString("OneHourAgoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 minute ago.
        /// </summary>
        public static string OneMinuteAgoText {
            get {
                return ResourceManager.GetString("OneMinuteAgoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 month ago.
        /// </summary>
        public static string OneMonthAgoText {
            get {
                return ResourceManager.GetString("OneMonthAgoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 year ago.
        /// </summary>
        public static string OneYearAgoText {
            get {
                return ResourceManager.GetString("OneYearAgoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pending approval.
        /// </summary>
        public static string PendingApprovalText {
            get {
                return ResourceManager.GetString("PendingApprovalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile.
        /// </summary>
        public static string ProfileAboutTitle {
            get {
                return ResourceManager.GetString("ProfileAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bookshelves.
        /// </summary>
        public static string ProfileBookshelvesTitle {
            get {
                return ResourceManager.GetString("ProfileBookshelvesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updates.
        /// </summary>
        public static string ProfileUpdatesTitle {
            get {
                return ResourceManager.GetString("ProfileUpdatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate the app.
        /// </summary>
        public static string RateButtonText {
            get {
                return ResourceManager.GetString("RateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} started reading:.
        /// </summary>
        public static string ReadStatusFeedItemCurrentlyReadingActionText {
            get {
                return ResourceManager.GetString("ReadStatusFeedItemCurrentlyReadingActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has read:.
        /// </summary>
        public static string ReadStatusFeedItemHasReadActionText {
            get {
                return ResourceManager.GetString("ReadStatusFeedItemHasReadActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} wants to read:.
        /// </summary>
        public static string ReadStatusFeedItemToReadActionText {
            get {
                return ResourceManager.GetString("ReadStatusFeedItemToReadActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from shelf.
        /// </summary>
        public static string RemoveFromShelfButtonText {
            get {
                return ResourceManager.GetString("RemoveFromShelfButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        public static string RetryLoginButtonText {
            get {
                return ResourceManager.GetString("RetryLoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} gave {1} stars to:.
        /// </summary>
        public static string ReviewFeedItemNStarRatingActionText {
            get {
                return ResourceManager.GetString("ReviewFeedItemNStarRatingActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} gave 1 star to: .
        /// </summary>
        public static string ReviewFeedItemOneStarRatingActionText {
            get {
                return ResourceManager.GetString("ReviewFeedItemOneStarRatingActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find books, authors.
        /// </summary>
        public static string SearchBoxPlaceholderText {
            get {
                return ResourceManager.GetString("SearchBoxPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refine:.
        /// </summary>
        public static string SearchFilterHeader {
            get {
                return ResourceManager.GetString("SearchFilterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search did not return any results.
        /// </summary>
        public static string SearchNoResultsMessage {
            get {
                return ResourceManager.GetString("SearchNoResultsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share.
        /// </summary>
        public static string SearchResultItemFlyoutShare {
            get {
                return ResourceManager.GetString("SearchResultItemFlyoutShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view author.
        /// </summary>
        public static string SearchResultItemFlyoutViewAuthor {
            get {
                return ResourceManager.GetString("SearchResultItemFlyoutViewAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to find books by title,author.
        /// </summary>
        public static string SearchTextBoxHint {
            get {
                return ResourceManager.GetString("SearchTextBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string SearchTitle {
            get {
                return ResourceManager.GetString("SearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pick a search type.
        /// </summary>
        public static string SearchTypeFullModeHeader {
            get {
                return ResourceManager.GetString("SearchTypeFullModeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A book has been shared with you.
        /// </summary>
        public static string ShareBookTitle {
            get {
                return ResourceManager.GetString("ShareBookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start sharing. Please try again later.
        /// </summary>
        public static string SharingFailedMessage {
            get {
                return ResourceManager.GetString("SharingFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is taking longer than expected. This could be due to a slow network connection..
        /// </summary>
        public static string SigningInStuckMessage {
            get {
                return ResourceManager.GetString("SigningInStuckMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        public static string TabHeaderCommunity {
            get {
                return ResourceManager.GetString("TabHeaderCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string TabHeaderHome {
            get {
                return ResourceManager.GetString("TabHeaderHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string TabHeaderMore {
            get {
                return ResourceManager.GetString("TabHeaderMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Books.
        /// </summary>
        public static string TabHeaderMyBooks {
            get {
                return ResourceManager.GetString("TabHeaderMyBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reads works best when you sign in to Goodreads to show you updates from your friends and people you follow..
        /// </summary>
        public static string TabHomeSignInText {
            get {
                return ResourceManager.GetString("TabHomeSignInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By logging in with your Goodreads account, you can personalize and organize your books. You can view all your bookshelves and you can update books that you are currently reading. You can also add or remove books from your shelves..
        /// </summary>
        public static string TabMyBooksSignInText {
            get {
                return ResourceManager.GetString("TabMyBooksSignInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string TopButtonText {
            get {
                return ResourceManager.GetString("TopButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        public static string UsernameText {
            get {
                return ResourceManager.GetString("UsernameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is on page {1} of {2} of:.
        /// </summary>
        public static string UserStatusFeedItemActionText {
            get {
                return ResourceManager.GetString("UserStatusFeedItemActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has finished reading:.
        /// </summary>
        public static string UserStatusFeedItemFinishedActionText {
            get {
                return ResourceManager.GetString("UserStatusFeedItemFinishedActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: 2.5.
        /// </summary>
        public static string VersionString {
            get {
                return ResourceManager.GetString("VersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view friends.
        /// </summary>
        public static string ViewFriendsText {
            get {
                return ResourceManager.GetString("ViewFriendsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view groups.
        /// </summary>
        public static string ViewGroupsText {
            get {
                return ResourceManager.GetString("ViewGroupsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view in goodreads.
        /// </summary>
        public static string ViewInGoodreadsText {
            get {
                return ResourceManager.GetString("ViewInGoodreadsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to read.
        /// </summary>
        public static string WantToReadButtonText {
            get {
                return ResourceManager.GetString("WantToReadButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s New.
        /// </summary>
        public static string WhatsNewHeader {
            get {
                return ResourceManager.GetString("WhatsNewHeader", resourceCulture);
            }
        }
    }
}
