//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epiphany.View.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epiphany.View.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add to shelf.
        /// </summary>
        public static string AddToShelfTitle {
            get {
                return ResourceManager.GetString("AddToShelfTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to age.
        /// </summary>
        public static string AgeText {
            get {
                return ResourceManager.GetString("AgeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string AppBarRefreshEventsButtonText {
            get {
                return ResourceManager.GetString("AppBarRefreshEventsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reads.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorite books.
        /// </summary>
        public static string FavoriteBooksText {
            get {
                return ResourceManager.GetString("FavoriteBooksText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friend status.
        /// </summary>
        public static string FriendStatusText {
            get {
                return ResourceManager.GetString("FriendStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friends.
        /// </summary>
        public static string FriendsTitle {
            get {
                return ResourceManager.GetString("FriendsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gender.
        /// </summary>
        public static string GenderText {
            get {
                return ResourceManager.GetString("GenderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to events.
        /// </summary>
        public static string HomeEventsTitle {
            get {
                return ResourceManager.GetString("HomeEventsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friends.
        /// </summary>
        public static string HomeFriendsTitle {
            get {
                return ResourceManager.GetString("HomeFriendsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to groups.
        /// </summary>
        public static string HomeGroupsTitle {
            get {
                return ResourceManager.GetString("HomeGroupsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my books.
        /// </summary>
        public static string HomeMyBooksTitle {
            get {
                return ResourceManager.GetString("HomeMyBooksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my profile.
        /// </summary>
        public static string HomeMyProfileTitle {
            get {
                return ResourceManager.GetString("HomeMyProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interests.
        /// </summary>
        public static string InterestsText {
            get {
                return ResourceManager.GetString("InterestsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to join date.
        /// </summary>
        public static string JoinDateText {
            get {
                return ResourceManager.GetString("JoinDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to like on facebook.
        /// </summary>
        public static string LikeonFBButtonText {
            get {
                return ResourceManager.GetString("LikeonFBButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location.
        /// </summary>
        public static string LocationText {
            get {
                return ResourceManager.GetString("LocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string MenuHeader {
            get {
                return ResourceManager.GetString("MenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no bookshelves!.
        /// </summary>
        public static string NoBookshelvesMessage {
            get {
                return ResourceManager.GetString("NoBookshelvesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no friends!.
        /// </summary>
        public static string NoFriendsMessage {
            get {
                return ResourceManager.GetString("NoFriendsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no updates!.
        /// </summary>
        public static string NoUpdatesMessage {
            get {
                return ResourceManager.GetString("NoUpdatesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friends.
        /// </summary>
        public static string NumberedItemFriendPlural {
            get {
                return ResourceManager.GetString("NumberedItemFriendPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friend.
        /// </summary>
        public static string NumberedItemFriendSingular {
            get {
                return ResourceManager.GetString("NumberedItemFriendSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to groups.
        /// </summary>
        public static string NumberedItemGroupPlural {
            get {
                return ResourceManager.GetString("NumberedItemGroupPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group.
        /// </summary>
        public static string NumberedItemGroupSingular {
            get {
                return ResourceManager.GetString("NumberedItemGroupSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pending approval.
        /// </summary>
        public static string PendingApprovalText {
            get {
                return ResourceManager.GetString("PendingApprovalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile.
        /// </summary>
        public static string ProfileAboutTitle {
            get {
                return ResourceManager.GetString("ProfileAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bookshelves.
        /// </summary>
        public static string ProfileBookshelvesTitle {
            get {
                return ResourceManager.GetString("ProfileBookshelvesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updates.
        /// </summary>
        public static string ProfileUpdatesTitle {
            get {
                return ResourceManager.GetString("ProfileUpdatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate the app.
        /// </summary>
        public static string RateButtonText {
            get {
                return ResourceManager.GetString("RateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retry.
        /// </summary>
        public static string RetryLoginButtonText {
            get {
                return ResourceManager.GetString("RetryLoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string SearchTitle {
            get {
                return ResourceManager.GetString("SearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is taking longer than expected. This could be due to a slow network connection..
        /// </summary>
        public static string SigningInStuckMessage {
            get {
                return ResourceManager.GetString("SigningInStuckMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        public static string UsernameText {
            get {
                return ResourceManager.GetString("UsernameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: 2.5.
        /// </summary>
        public static string VersionString {
            get {
                return ResourceManager.GetString("VersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view friends.
        /// </summary>
        public static string ViewFriendsText {
            get {
                return ResourceManager.GetString("ViewFriendsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view groups.
        /// </summary>
        public static string ViewGroupsText {
            get {
                return ResourceManager.GetString("ViewGroupsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view in goodreads.
        /// </summary>
        public static string ViewInGoodreadsText {
            get {
                return ResourceManager.GetString("ViewInGoodreadsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s New.
        /// </summary>
        public static string WhatsNewHeader {
            get {
                return ResourceManager.GetString("WhatsNewHeader", resourceCulture);
            }
        }
    }
}
